### ISSUE TITLE
Add a `humans.txt` file

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe-site#351] opened 2016-09-20 12:26 UTC
For humans

**Comment by marti1125** [comment] 2017-04-07 05:32
@cvan something like this http://humanstxt.org/ =?

**Comment by cvan** [comment] 2017-04-07 05:58
Yep 👍

**Comment by marti1125** [comment] 2017-04-07 06:01
what kind of information it will have? following the standard (Authors, and contributors) could be
http://humanstxt.org/Standard.html
and an example https://www.farmacia.bio/humans.txt

**Comment by cvan** [comment] 2017-04-07 06:04
It's not in `humans.txt` format, but I'd include similar info. as in https://addons.mozilla.org/contribute.json

**Comment by amitsin6h** [comment] 2017-06-10 08:37
want to work assign me @cvan

**Comment by dmarcos** [comment] 2017-06-10 16:10
@amitsin6h Feel free to start working an any of the issues that are open. Assigning the issue is just a way to mark that someone is already working on it and people don't step on each other's toes. We don't have a problem right now with multiple people wanting to pick the same issues. You can fix as many bugs as you want but I would just pick one at a time (I've seen you have requested to be assigned to a bunch of them). Looking forward to seeing your PRs.

**Comment by amitsin6h** [comment] 2017-06-10 17:14
is their any irc channel @dmarcos

**Comment by dmarcos** [comment] 2017-06-10 17:23
@amitsin6h We have a Slack setup:

https://aframe.io/community/#slack

See you there.

**Comment by ngokevin** [comment] 2017-06-30 07:31
Marking won't fix, we have the community page and a humans.txt file would be additional to maintain.

**Closed by ngokevin** 2017-06-30 07:31 UTC
Labels: help wanted (easy)
